// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0FtH49eFmiowxZFkIX2Lw2VQgaxZMmaU',
    appId: '1:912962287480:web:b2a5de86db9188f71aba8d',
    messagingSenderId: '912962287480',
    projectId: 'lifeinsync-bc99c',
    authDomain: 'lifeinsync-bc99c.firebaseapp.com',
    storageBucket: 'lifeinsync-bc99c.firebasestorage.app',
    measurementId: 'G-RPVVYYNV38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkA3kK8NqdRRlBK_Fsb4dAhAyUfPrMlcQ',
    appId: '1:912962287480:android:64414e71004fa3271aba8d',
    messagingSenderId: '912962287480',
    projectId: 'lifeinsync-bc99c',
    storageBucket: 'lifeinsync-bc99c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK-e_nbO7QSz_udU4_xLIKnUPme_umH3o',
    appId: '1:912962287480:ios:9530bee2769adc771aba8d',
    messagingSenderId: '912962287480',
    projectId: 'lifeinsync-bc99c',
    storageBucket: 'lifeinsync-bc99c.firebasestorage.app',
    iosClientId: '912962287480-d97givufiqjt15vs3nbo2hhbdvm4uuqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeinsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK-e_nbO7QSz_udU4_xLIKnUPme_umH3o',
    appId: '1:912962287480:ios:9530bee2769adc771aba8d',
    messagingSenderId: '912962287480',
    projectId: 'lifeinsync-bc99c',
    storageBucket: 'lifeinsync-bc99c.firebasestorage.app',
    iosClientId: '912962287480-d97givufiqjt15vs3nbo2hhbdvm4uuqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeinsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0FtH49eFmiowxZFkIX2Lw2VQgaxZMmaU',
    appId: '1:912962287480:web:f2b1dfc7a9fbc0851aba8d',
    messagingSenderId: '912962287480',
    projectId: 'lifeinsync-bc99c',
    authDomain: 'lifeinsync-bc99c.firebaseapp.com',
    storageBucket: 'lifeinsync-bc99c.firebasestorage.app',
    measurementId: 'G-ZT51RGJ27S',
  );
}
