import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('hi'),
    Locale('gu'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(localizations != null, 'AppLocalizations not found in context');
    return localizations!;
  }

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'welcomeBack': 'Welcome Back',
      'signInJourney': 'Sign in to continue your journey',
      'settings': 'Settings',
      'email': 'Email',
      'password': 'Password',
      'forgotPassword': 'Forgot password?',
      'signIn': 'Sign In',
      'or': 'or',
      'google': 'Google',
      'phoneOtp': 'Phone OTP',
      'dontHaveAccount': "Don't have an account?",
      'signUp': 'Sign Up',
      'enterEmail': 'Please enter your email',
      'validEmail': 'Enter a valid email',
      'enterPassword': 'Please enter your password',
      'min6Chars': 'Minimum 6 characters',
      'enterEmailFirst': 'Enter your email above first',
      'passwordResetSent': 'Password reset email sent!',
      'createAccount': 'Create account',
      'startJourneyToday': 'Start your wellbeing journey today',
      'fullName': 'Full Name',
      'yourName': 'Your name',
      'enterName': 'Enter your name',
      'mobileNumber': 'Mobile Number',
      'enterMobileNumber': 'Enter your mobile number',
      'useCountryCode': 'Use country code, e.g. +91 9876543210',
      'enterValidMobile': 'Enter a valid mobile number',
      'passwordMin6': 'Password must be at least 6 characters',
      'confirmPassword': 'Confirm Password',
      'reenterPassword': 'Re-enter password',
      'passwordsNoMatch': 'Passwords do not match',
      'agreeTo': 'I agree to the ',
      'termsOfService': 'Terms of Service',
      'and': ' and ',
      'privacyPolicy': 'Privacy Policy',
      'alreadyHaveAccount': 'Already have an account?',
      'createAccountButton': 'Create Account',
      'agreeTermsError': 'Please agree to the Terms of Service',
      'continue': 'Continue',
      'confirm': 'Confirm',
      'setDailyFocusGoal': 'Set your daily focus goal',
      'chooseFocusMinutes': 'Choose how many focused minutes you aim for each day.',
      'minutes': 'minutes',
      'setDailyScreenLimit': 'Set a daily screen limit',
      'warnCloseLimit': 'We will warn you when you are close to this limit.',
      'hours': 'hours',
      'dailyScreenLimit': 'Daily screen limit',
      'notifications': 'Notifications',
      'notificationsSubtitle': 'Habit reminders and wellbeing alerts',
      'theme': 'Theme',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'language': 'Language',
      'english': 'English',
      'hindi': 'Hindi',
      'gujarati': 'Gujarati',
        'home': 'Home',
        'usage': 'Usage',
        'profile': 'Profile',
        'insights': 'Insights',
        'menu': 'Menu',
        'signOut': 'Sign Out',
        'cancel': 'Cancel',
        'signOutConfirmTitle': 'Sign Out',
        'signOutConfirmMessage': 'Are you sure you want to sign out?',
        'logoutFailed': 'Logout failed',
        'name': 'Name',
        'avatar': 'Avatar',
        'timezone': 'Timezone',
        'gender': 'Gender',
        'selectGender': 'Select gender',
        'male': 'Male',
        'female': 'Female',
        'other': 'Other',
        'preferNotToSay': 'Prefer not to say',
        'age': 'Age',
        'enterAgeHint': 'Enter age (1-120)',
        'saveProfile': 'Save Profile',
        'profileUpdated': 'Profile updated',
        'screenTimeTitle': 'Screen Time',
        'screenTimeSubtitle': "Here\'s how you used your phone",
        'appBreakdown': 'App Breakdown',
        'noUsageToday': 'No app usage captured yet for today.',
        'grantUsagePermission': 'Grant usage permission to see app breakdown.',
        'usageAccessNeeded': 'Usage Access Needed',
        'usageAccessPrompt':
          'Enable usage access in Android settings to read real screen time data.',
        'openSettings': 'Open Settings',
        'refresh': 'Refresh',
        'backgroundSyncUnavailable': 'Background sync not available yet.',
        'lastBackgroundSync': 'Last background sync',
        'trackedApps': 'tracked apps',
        'today': 'today',
        'signInToViewInsights': 'Sign in to view insights.',
        'insightsLoadFailed': 'Could not load insights right now.',
        'insightsSubtitle': 'Your weekly wellbeing report',
        'noInsightsYet': 'No insights yet',
        'unlockInsightsHint':
          'Complete a focus session, log habits, and use the app for a day to unlock trends.',
        'thisWeek': 'This Week',
        'thisMonth': 'This Month',
        'overDailyLimit': 'Over daily limit',
        'withinDailyLimit': 'Within daily limit',
        'tapBarToInspectDay': 'Tap any bar to inspect a day',
        'setDailyScreenTimeHint': 'Set how much screen time you want per day',
        'signInToViewHabits': 'Sign in to view your habits.',
        'productive': 'Productive',
        'entertainment': 'Entertainment',
        'social': 'Social',
        'focusMode': 'Focus Mode',
        'fatigueTracker': 'Fatigue Tracker',
        'habits': 'Daily Rhythm',
        'appCategorizer': 'App Categorizer',
        'fatigueAutoDetected': 'Auto-detected from your usage patterns',
        'fatigueUsageLimited': 'Usage access is not enabled. Fatigue score currently uses limited data.',
        'enable': 'Enable',
        'fatigueLevelFresh': 'Fresh',
        'fatigueLevelMild': 'Mildly Tired',
        'fatigueLevelModerate': 'Moderately Fatigued',
        'fatigueLevelHigh': 'High Fatigue',
        'fatigueRecoFresh': 'You are in great shape! Your digital habits are healthy today.',
        'fatigueRecoMild': 'Mild fatigue detected. Try a short walk or stretch break.',
        'fatigueRecoModerate': 'Moderate fatigue. Step away from screens for 30+ minutes.',
        'fatigueRecoHigh': 'High digital fatigue. Rest your eyes, go outside, and avoid screens for a while.',
        'after10pm': 'after 10pm',
        'withoutBreak': 'without break',
        'fatigueTriggerHighScreenTime': 'High screen time',
        'fatigueTriggerLateNight': 'Late-night usage detected',
        'fatigueTriggerLongSession': 'Long unbroken session',
        'fatigueTriggerHeavyDraining': 'Heavy social/entertainment use',
        'fatigueTriggerNoFocusToday': 'No focus sessions completed today',
        'fatigueScore': 'Fatigue Score',
        'scoreBreakdown': 'Score Breakdown',
        'drainingApps': 'Draining Apps',
        'lateNightUse': 'Late-Night Use',
        'longSessions': 'Long Sessions',
        'healthyHabitsMinus': 'Healthy Habits (-)',
        'fatigueHistory7Days': '7-Day Fatigue History',
        'noFatigueDataYet': 'No logged fatigue data yet. Keep using the app and this chart will fill with your real pattern.',
        'fatigueTriggers': 'Fatigue Triggers',
        'recommendation': 'Recommendation',
        'mon': 'Mon',
        'tue': 'Tue',
        'wed': 'Wed',
        'thu': 'Thu',
        'fri': 'Fri',
        'sat': 'Sat',
        'sun': 'Sun',
        'appCategories': 'App Categories',
        'autoCategorizedByUsage': 'Auto-categorized by usage patterns',
        'usageHealth': 'Usage Health',
        'healthy': 'healthy',
        'draining': 'Draining',
        'categoryBreakdown': 'Category Breakdown',
        'all': 'All',
        'grantUsagePermissionCategories': 'Grant usage permission to see app categories.',
        'habitsSubtitle': 'Build your daily rhythm',
        'todaysHabits': "Today's Habits",
        'noHabitsYet': 'No habits yet',
        'tapAddHabitFirst': 'Tap Add Habit to create your first routine.',
        'todayProgress': "Today's Progress",
        'complete': 'complete',
        'totalStreakDays': 'total streak days',
        'addHabit': 'Add Habit',
        'newHabit': 'New Habit',
        'chooseEmoji': 'Choose an emoji',
        'habitName': 'Habit name',
        'habitNameHint': 'e.g. Drink water, Exercise...',
        'reminderTime': 'Reminder time',
        'setRepeatInterval': 'Set repeat interval',
        'repeatEveryMinutes': 'Repeat every {minutes} minutes',
        'noRepeatInterval': 'No repeat interval',
        'editHabit': 'Edit Habit',
        'removeHabit': 'Remove habit',
        'confirmRemoveHabit': 'Remove "{name}" and cancel its reminders?',
        'dayStreak': 'day streak',
        'past7Days': 'Past 7 days',
        'past30Days': 'Past 30 days',
        'noHabitLogsYet': 'No completed habit logs in this period yet.',
        'weeklyInsights': 'Weekly Insights',
        'avgScore': 'Avg Score',
        'avgFatigue': 'Avg Fatigue',
        'focusShort': 'Focus',
        'wellbeingWord': 'wellbeing',
        'thisWeekLower': 'this week',
        'thisMonthLower': 'this month',
        'wellbeingTrend': 'Wellbeing Trend',
        'weeklyAppUsageBreakdown': 'Weekly app usage breakdown',
        'productiveVsDraining': 'Productive vs Draining',
        'friend': 'Friend',
        'goodMorning': 'Good morning',
        'goodAfternoon': 'Good afternoon',
        'goodEvening': 'Good evening',
        'focusModeSubtitleBreak': 'Take a breather',
        'focusModeSubtitleFocus': 'Stay in the zone',
        'sessionsToday': 'Sessions today',
        'focusedToday': 'Focused today',
        'breakTime': 'Break time',
        'sessionDurations': 'Session Durations',
        'adjustTimesRoutine': 'Adjust times to match your routine.',
        'resetDefaults': 'Reset defaults',
        'durationsReset': 'Focus durations reset to defaults.',
        'sessionCompleteTakeBreak': 'Session complete! Take a break.',
        'breakOverReadyFocus': 'Break over. Ready to focus?',
        'minutesShort': 'min',
        'readyToFocus': 'Ready to focus?',
        'startPomodoro': 'Start a Pomodoro session',
        'start': 'Start',
        'cloudSynced': 'Cloud synced',
        'pendingUpload': 'Pending upload',
        'usingOfflineCache': 'Using offline cache',
        'waitingFirstSync': 'Waiting for first background sync...',
        'lastSync': 'Last sync',
        'trackedAppsTitle': 'Tracked apps',
        'habitConsistency': 'Habit Consistency',
        'daysWord': 'days',
        'insightAvgWellbeingPrefix': 'Your average wellbeing this period is',
        'insightAvgFatiguePrefix': 'Average fatigue is',
        'insightOutOf100': 'out of 100',
        'insightFocusCompletedPrefix': 'You completed',
        'insightFocusCompletedSuffix': 'of focus sessions in the last',
        'insightProductiveRatioPrefix': 'Productive usage ratio is',
        'insightProductiveRatioSuffix': 'based on your logged data',
        'wellbeingScore': 'Wellbeing Score',
        'basedOnTodaysFatigue': "Based on today's fatigue score",
        'noHabitsHomeHint': 'No habits yet. Add habits in Daily Rhythm tab and they will appear here instantly.',
        'fatigueHighHint': 'Take a break and reduce draining app use.',
        'fatigueModerateHint': 'You may benefit from a short recovery break.',
        'fatigueMildHint': 'Good balance. Keep screen use mindful.',
        'fatigueLowLabel': 'Low Fatigue',
        'fatigueLowHint': 'Great energy pattern so far today.',
        'doneWord': 'done',
        'pomodoro': 'Pomodoro',
        'deepWork': 'Deep Work',
        'flowState': 'Flow State',
        'focusTip1': 'Put your phone face-down during sessions',
        'focusTip2': 'Try lo-fi music to help concentration',
        'focusTip3': 'Keep water nearby to stay hydrated',
        'focusTip4': 'A plant on your desk reduces stress',
        'focusTip5': 'Enable Do Not Disturb before starting',
    },
    'hi': {
      'welcomeBack': 'वापसी पर स्वागत है',
      'signInJourney': 'अपनी यात्रा जारी रखने के लिए साइन इन करें',
      'settings': 'सेटिंग्स',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'forgotPassword': 'पासवर्ड भूल गए?',
      'signIn': 'साइन इन',
      'or': 'या',
      'google': 'गूगल',
      'phoneOtp': 'फोन ओटीपी',
      'dontHaveAccount': 'क्या आपका खाता नहीं है?',
      'signUp': 'साइन अप',
      'enterEmail': 'कृपया अपना ईमेल दर्ज करें',
      'validEmail': 'मान्य ईमेल दर्ज करें',
      'enterPassword': 'कृपया अपना पासवर्ड दर्ज करें',
      'min6Chars': 'कम से कम 6 अक्षर',
      'enterEmailFirst': 'पहले ऊपर अपना ईमेल दर्ज करें',
      'passwordResetSent': 'पासवर्ड रीसेट ईमेल भेजा गया!',
      'createAccount': 'खाता बनाएं',
      'startJourneyToday': 'आज ही अपनी वेलबीइंग यात्रा शुरू करें',
      'fullName': 'पूरा नाम',
      'yourName': 'आपका नाम',
      'enterName': 'अपना नाम दर्ज करें',
      'mobileNumber': 'मोबाइल नंबर',
      'enterMobileNumber': 'अपना मोबाइल नंबर दर्ज करें',
      'useCountryCode': 'देश कोड का उपयोग करें, जैसे +91 9876543210',
      'enterValidMobile': 'मान्य मोबाइल नंबर दर्ज करें',
      'passwordMin6': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
      'confirmPassword': 'पासवर्ड पुष्टि करें',
      'reenterPassword': 'पासवर्ड फिर से दर्ज करें',
      'passwordsNoMatch': 'पासवर्ड मेल नहीं खाते',
      'agreeTo': 'मैं सहमत हूं ',
      'termsOfService': 'सेवा की शर्तों',
      'and': ' और ',
      'privacyPolicy': 'गोपनीयता नीति',
      'alreadyHaveAccount': 'क्या आपके पास पहले से खाता है?',
      'createAccountButton': 'खाता बनाएं',
      'agreeTermsError': 'कृपया सेवा की शर्तों से सहमत हों',
      'continue': 'जारी रखें',
      'confirm': 'पुष्टि करें',
      'setDailyFocusGoal': 'अपना दैनिक फोकस लक्ष्य तय करें',
      'chooseFocusMinutes': 'हर दिन के लिए कितने फोकस मिनट चाहिए चुनें।',
      'minutes': 'मिनट',
      'setDailyScreenLimit': 'दैनिक स्क्रीन सीमा तय करें',
      'warnCloseLimit': 'सीमा के करीब होने पर हम आपको चेतावनी देंगे।',
      'hours': 'घंटे',
      'dailyScreenLimit': 'दैनिक स्क्रीन सीमा',
      'notifications': 'सूचनाएं',
      'notificationsSubtitle': 'आदत रिमाइंडर और वेलबीइंग अलर्ट',
      'theme': 'थीम',
      'light': 'लाइट',
      'dark': 'डार्क',
      'system': 'सिस्टम',
      'language': 'भाषा',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'gujarati': 'गुजराती',
        'home': 'होम',
        'usage': 'उपयोग',
        'profile': 'प्रोफाइल',
        'insights': 'इनसाइट्स',
        'menu': 'मेनू',
        'signOut': 'साइन आउट',
        'cancel': 'रद्द करें',
        'signOutConfirmTitle': 'साइन आउट',
        'signOutConfirmMessage': 'क्या आप वाकई साइन आउट करना चाहते हैं?',
        'logoutFailed': 'लॉगआउट विफल',
        'name': 'नाम',
        'avatar': 'अवतार',
        'timezone': 'टाइम ज़ोन',
        'gender': 'लिंग',
        'selectGender': 'लिंग चुनें',
        'male': 'पुरुष',
        'female': 'महिला',
        'other': 'अन्य',
        'preferNotToSay': 'कहना नहीं चाहते',
        'age': 'उम्र',
        'enterAgeHint': 'उम्र दर्ज करें (1-120)',
        'saveProfile': 'प्रोफाइल सेव करें',
        'profileUpdated': 'प्रोफाइल अपडेट हो गई',
        'screenTimeTitle': 'स्क्रीन टाइम',
        'screenTimeSubtitle': 'यह है आपने फोन कैसे उपयोग किया',
        'appBreakdown': 'ऐप विवरण',
        'noUsageToday': 'आज के लिए अभी ऐप उपयोग डेटा उपलब्ध नहीं है।',
        'grantUsagePermission': 'ऐप विवरण देखने के लिए उपयोग अनुमति दें।',
        'usageAccessNeeded': 'यूसेज एक्सेस आवश्यक है',
        'usageAccessPrompt':
          'वास्तविक स्क्रीन टाइम डेटा पढ़ने के लिए Android सेटिंग्स में usage access सक्षम करें।',
        'openSettings': 'सेटिंग्स खोलें',
        'refresh': 'रीफ्रेश',
        'backgroundSyncUnavailable': 'बैकग्राउंड सिंक अभी उपलब्ध नहीं है।',
        'lastBackgroundSync': 'पिछला बैकग्राउंड सिंक',
        'trackedApps': 'ट्रैक किए गए ऐप्स',
        'today': 'आज',
        'signInToViewInsights': 'इनसाइट्स देखने के लिए साइन इन करें।',
        'insightsLoadFailed': 'इस समय इनसाइट्स लोड नहीं हो सकीं।',
        'insightsSubtitle': 'आपकी साप्ताहिक वेलबीइंग रिपोर्ट',
        'noInsightsYet': 'अभी तक कोई इनसाइट्स नहीं',
        'unlockInsightsHint':
          'फोकस सेशन पूरा करें, आदतें लॉग करें और रुझान देखने के लिए एक दिन ऐप का उपयोग करें।',
        'thisWeek': 'यह सप्ताह',
        'thisMonth': 'यह महीना',
        'overDailyLimit': 'दैनिक सीमा से अधिक',
        'withinDailyLimit': 'दैनिक सीमा के भीतर',
        'tapBarToInspectDay': 'किसी दिन का विवरण देखने के लिए बार पर टैप करें',
        'setDailyScreenTimeHint': 'प्रतिदिन कितना स्क्रीन समय चाहिए, सेट करें',
        'signInToViewHabits': 'अपनी आदतें देखने के लिए साइन इन करें।',
        'productive': 'उत्पादक',
        'entertainment': 'मनोरंजन',
        'social': 'सोशल',
        'focusMode': 'फोकस मोड',
        'fatigueTracker': 'थकान ट्रैकर',
        'habits': 'Daily Rhythm',
        'appCategorizer': 'ऐप वर्गीकरण',
        'fatigueAutoDetected': 'आपके उपयोग पैटर्न से स्वतः पहचाना गया',
        'fatigueUsageLimited': 'यूसेज एक्सेस सक्षम नहीं है। थकान स्कोर सीमित डेटा पर आधारित है।',
        'enable': 'सक्षम करें',
        'fatigueLevelFresh': 'तरोताज़ा',
        'fatigueLevelMild': 'हल्की थकान',
        'fatigueLevelModerate': 'मध्यम थकान',
        'fatigueLevelHigh': 'उच्च थकान',
        'fatigueRecoFresh': 'आप अच्छी स्थिति में हैं! आपकी डिजिटल आदतें आज स्वस्थ हैं।',
        'fatigueRecoMild': 'हल्की थकान मिली। थोड़ी वॉक या स्ट्रेच करें।',
        'fatigueRecoModerate': 'मध्यम थकान। 30+ मिनट स्क्रीन से दूर रहें।',
        'fatigueRecoHigh': 'उच्च डिजिटल थकान। आंखों को आराम दें और थोड़ी देर स्क्रीन से दूर रहें।',
        'after10pm': 'रात 10 बजे के बाद',
        'withoutBreak': 'बिना ब्रेक',
        'fatigueTriggerHighScreenTime': 'उच्च स्क्रीन समय',
        'fatigueTriggerLateNight': 'लेट-नाइट उपयोग पाया गया',
        'fatigueTriggerLongSession': 'लंबा बिना रुके सत्र',
        'fatigueTriggerHeavyDraining': 'सोशल/मनोरंजन उपयोग अधिक',
        'fatigueTriggerNoFocusToday': 'आज कोई फोकस सत्र पूरा नहीं हुआ',
        'fatigueScore': 'थकान स्कोर',
        'scoreBreakdown': 'स्कोर विवरण',
        'drainingApps': 'थकाने वाले ऐप्स',
        'lateNightUse': 'लेट-नाइट उपयोग',
        'longSessions': 'लंबे सत्र',
        'healthyHabitsMinus': 'स्वस्थ आदतें (-)',
        'fatigueHistory7Days': '7-दिन थकान इतिहास',
        'noFatigueDataYet': 'अभी थकान डेटा लॉग नहीं हुआ है। ऐप का उपयोग जारी रखें, चार्ट भर जाएगा।',
        'fatigueTriggers': 'थकान ट्रिगर्स',
        'recommendation': 'सुझाव',
        'mon': 'सोम',
        'tue': 'मंगल',
        'wed': 'बुध',
        'thu': 'गुरु',
        'fri': 'शुक्र',
        'sat': 'शनि',
        'sun': 'रवि',
        'appCategories': 'ऐप वर्गीकरण',
        'autoCategorizedByUsage': 'उपयोग पैटर्न से स्वतः वर्गीकृत',
        'usageHealth': 'उपयोग स्वास्थ्य',
        'healthy': 'स्वस्थ',
        'draining': 'थकाने वाला',
        'categoryBreakdown': 'श्रेणी विवरण',
        'all': 'सभी',
        'grantUsagePermissionCategories': 'ऐप श्रेणियां देखने के लिए उपयोग अनुमति दें।',
        'habitsSubtitle': 'अपनी दैनिक दिनचर्या बनाएं',
        'todaysHabits': 'आज की आदतें',
        'noHabitsYet': 'अभी कोई आदत नहीं',
        'tapAddHabitFirst': 'अपनी पहली आदत बनाने के लिए Add Habit दबाएं।',
        'todayProgress': 'आज की प्रगति',
        'complete': 'पूर्ण',
        'totalStreakDays': 'कुल स्ट्रीक दिन',
        'addHabit': 'आदत जोड़ें',
        'newHabit': 'नई आदत',
        'chooseEmoji': 'इमोजी चुनें',
        'habitName': 'आदत का नाम',
        'habitNameHint': 'जैसे: पानी पीना, व्यायाम...',
        'reminderTime': 'रिमाइंडर समय',
        'setRepeatInterval': 'रिपीट अंतराल सेट करें',
        'repeatEveryMinutes': 'हर {minutes} मिनट में दोहराएं',
        'noRepeatInterval': 'कोई रिपीट अंतराल नहीं',
        'editHabit': 'आदत संपादित करें',
        'removeHabit': 'आदत हटाएं',
        'confirmRemoveHabit': '"{name}" को हटाएं और इसके रिमाइंडर रद्द करें?',
        'dayStreak': 'दिन स्ट्रीक',
        'past7Days': 'पिछले 7 दिन',
        'past30Days': 'पिछले 30 दिन',
        'noHabitLogsYet': 'इस अवधि में अभी कोई आदत लॉग नहीं है।',
        'weeklyInsights': 'साप्ताहिक इनसाइट्स',
        'avgScore': 'औसत स्कोर',
        'avgFatigue': 'औसत थकान',
        'focusShort': 'फोकस',
        'wellbeingWord': 'वेलबीइंग',
        'thisWeekLower': 'इस सप्ताह',
        'thisMonthLower': 'इस महीने',
        'wellbeingTrend': 'वेलबीइंग ट्रेंड',
        'weeklyAppUsageBreakdown': 'साप्ताहिक ऐप उपयोग विवरण',
        'productiveVsDraining': 'उत्पादक बनाम थकाने वाला',
        'friend': 'मित्र',
        'goodMorning': 'सुप्रभात',
        'goodAfternoon': 'नमस्कार',
        'goodEvening': 'शुभ संध्या',
        'focusModeSubtitleBreak': 'थोड़ा आराम करें',
        'focusModeSubtitleFocus': 'फोकस में रहें',
        'sessionsToday': 'आज सत्र',
        'focusedToday': 'आज फोकस समय',
        'breakTime': 'ब्रेक समय',
        'sessionDurations': 'सत्र अवधि',
        'adjustTimesRoutine': 'समय अपनी दिनचर्या के अनुसार बदलें।',
        'resetDefaults': 'डिफॉल्ट रीसेट करें',
        'durationsReset': 'फोकस अवधि डिफॉल्ट पर रीसेट हुई।',
        'sessionCompleteTakeBreak': 'सत्र पूरा! ब्रेक लें।',
        'breakOverReadyFocus': 'ब्रेक खत्म। फोकस के लिए तैयार?',
        'minutesShort': 'मिन',
        'readyToFocus': 'फोकस के लिए तैयार?',
        'startPomodoro': 'पोमोडोरो सत्र शुरू करें',
        'start': 'शुरू',
        'cloudSynced': 'क्लाउड सिंक',
        'pendingUpload': 'अपलोड लंबित',
        'usingOfflineCache': 'ऑफलाइन कैश उपयोग में',
        'waitingFirstSync': 'पहले बैकग्राउंड सिंक का इंतज़ार...',
        'lastSync': 'अंतिम सिंक',
        'trackedAppsTitle': 'ट्रैक किए गए ऐप्स',
        'habitConsistency': 'आदत निरंतरता',
        'daysWord': 'दिन',
        'insightAvgWellbeingPrefix': 'इस अवधि में आपकी औसत वेलबीइंग है',
        'insightAvgFatiguePrefix': 'औसत थकान है',
        'insightOutOf100': '100 में से',
        'insightFocusCompletedPrefix': 'आपने पूरा किया',
        'insightFocusCompletedSuffix': 'फोकस सत्र पिछले',
        'insightProductiveRatioPrefix': 'उत्पादक उपयोग अनुपात',
        'insightProductiveRatioSuffix': 'आपके लॉग डेटा पर आधारित है',
        'wellbeingScore': 'वेलबीइंग स्कोर',
        'basedOnTodaysFatigue': 'आज के थकान स्कोर पर आधारित',
        'noHabitsHomeHint': 'अभी कोई आदत नहीं। Daily Rhythm टैब में जोड़ें, यहां तुरंत दिखेगी।',
        'fatigueHighHint': 'ब्रेक लें और थकाने वाले ऐप उपयोग कम करें।',
        'fatigueModerateHint': 'छोटा रिकवरी ब्रेक आपके लिए अच्छा रहेगा।',
        'fatigueMildHint': 'अच्छा संतुलन है। स्क्रीन उपयोग संतुलित रखें।',
        'fatigueLowLabel': 'कम थकान',
        'fatigueLowHint': 'आज आपकी ऊर्जा पैटर्न बहुत अच्छा है।',
        'doneWord': 'पूर्ण',
        'pomodoro': 'पोमोडोरो',
        'deepWork': 'डीप वर्क',
        'flowState': 'फ्लो स्टेट',
        'focusTip1': 'सत्र के दौरान फोन को उल्टा रखें',
        'focusTip2': 'ध्यान के लिए लो-फाई संगीत आजमाएं',
        'focusTip3': 'हाइड्रेटेड रहने के लिए पानी पास रखें',
        'focusTip4': 'डेस्क पर पौधा तनाव कम करता है',
        'focusTip5': 'शुरू करने से पहले Do Not Disturb चालू करें',
    },
    'gu': {
      'welcomeBack': 'પાછા આવવા બદલ સ્વાગત',
      'signInJourney': 'તમારી સફર ચાલુ રાખવા સાઇન ઇન કરો',
      'settings': 'સેટિંગ્સ',
      'email': 'ઈમેઇલ',
      'password': 'પાસવર્ડ',
      'forgotPassword': 'પાસવર્ડ ભૂલી ગયા?',
      'signIn': 'સાઇન ઇન',
      'or': 'અથવા',
      'google': 'ગૂગલ',
      'phoneOtp': 'ફોન OTP',
      'dontHaveAccount': 'એકાઉન્ટ નથી?',
      'signUp': 'સાઇન અપ',
      'enterEmail': 'કૃપા કરીને ઈમેઇલ દાખલ કરો',
      'validEmail': 'માન્ય ઈમેઇલ દાખલ કરો',
      'enterPassword': 'કૃપા કરીને પાસવર્ડ દાખલ કરો',
      'min6Chars': 'ઓછામાં ઓછા 6 અક્ષરો',
      'enterEmailFirst': 'પહેલા ઉપર ઈમેઇલ દાખલ કરો',
      'passwordResetSent': 'પાસવર્ડ રીસેટ ઈમેઇલ મોકલાઈ ગયો!',
      'createAccount': 'એકાઉન્ટ બનાવો',
      'startJourneyToday': 'આજે જ તમારી વેલબીંગ સફર શરૂ કરો',
      'fullName': 'પૂરું નામ',
      'yourName': 'તમારું નામ',
      'enterName': 'તમારું નામ દાખલ કરો',
      'mobileNumber': 'મોબાઇલ નંબર',
      'enterMobileNumber': 'તમારો મોબાઇલ નંબર દાખલ કરો',
      'useCountryCode': 'દેશ કોડ સાથે લખો, જેમ કે +91 9876543210',
      'enterValidMobile': 'માન્ય મોબાઇલ નંબર દાખલ કરો',
      'passwordMin6': 'પાસવર્ડ ઓછામાં ઓછા 6 અક્ષરનો હોવો જોઈએ',
      'confirmPassword': 'પાસવર્ડની પુષ્ટિ કરો',
      'reenterPassword': 'પાસવર્ડ ફરીથી દાખલ કરો',
      'passwordsNoMatch': 'પાસવર્ડ મેળ ખાતા નથી',
      'agreeTo': 'હું સંમત છું ',
      'termsOfService': 'સેવાની શરતો',
      'and': ' અને ',
      'privacyPolicy': 'પ્રાઇવસી પોલિસી',
      'alreadyHaveAccount': 'પહેલેથી એકાઉન્ટ છે?',
      'createAccountButton': 'એકાઉન્ટ બનાવો',
      'agreeTermsError': 'કૃપા કરીને સેવાની શરતો માનો',
      'continue': 'ચાલુ રાખો',
      'confirm': 'પુષ્ટિ કરો',
      'setDailyFocusGoal': 'તમારો દૈનિક ફોકસ લક્ષ્ય સેટ કરો',
      'chooseFocusMinutes': 'દરરોજ કેટલા ફોકસ મિનિટ જોઈએ તે પસંદ કરો.',
      'minutes': 'મિનિટ',
      'setDailyScreenLimit': 'દૈનિક સ્ક્રીન મર્યાદા સેટ કરો',
      'warnCloseLimit': 'તમે મર્યાદા નજીક આવો ત્યારે અમે ચેતવણી આપીશું.',
      'hours': 'કલાક',
      'dailyScreenLimit': 'દૈનિક સ્ક્રીન મર્યાદા',
      'notifications': 'સૂચનાઓ',
      'notificationsSubtitle': 'હેબિટ રિમાઇન્ડર અને વેલબીંગ એલર્ટ',
      'theme': 'થીમ',
      'light': 'લાઇટ',
      'dark': 'ડાર્ક',
      'system': 'સિસ્ટમ',
      'language': 'ભાષા',
      'english': 'અંગ્રેજી',
      'hindi': 'હિન્દી',
      'gujarati': 'ગુજરાતી',
      'home': 'હોમ',
      'usage': 'ઉપયોગ',
      'profile': 'પ્રોફાઇલ',
      'insights': 'ઇન્સાઇટ્સ',
      'menu': 'મેનુ',
      'signOut': 'સાઇન આઉટ',
      'cancel': 'રદ કરો',
      'signOutConfirmTitle': 'સાઇન આઉટ',
      'signOutConfirmMessage': 'શું તમે ખરેખર સાઇન આઉટ કરવા માંગો છો?',
      'logoutFailed': 'લૉગઆઉટ નિષ્ફળ ગયું',
      'name': 'નામ',
      'avatar': 'અવતાર',
      'timezone': 'ટાઇમઝોન',
      'gender': 'લિંગ',
      'selectGender': 'લિંગ પસંદ કરો',
      'male': 'પુરુષ',
      'female': 'સ્ત્રી',
      'other': 'અન્ય',
      'preferNotToSay': 'કહેવું નથી',
      'age': 'ઉંમર',
      'enterAgeHint': 'ઉંમર દાખલ કરો (1-120)',
      'saveProfile': 'પ્રોફાઇલ સેવ કરો',
      'profileUpdated': 'પ્રોફાઇલ અપડેટ થઈ',
      'screenTimeTitle': 'સ્ક્રીન સમય',
      'screenTimeSubtitle': 'તમે ફોન કેવી રીતે ઉપયોગ કર્યો તેનો સારાંશ',
      'appBreakdown': 'એપ વિગત',
      'noUsageToday': 'આજ માટે હજુ એપ ઉપયોગ ડેટા નથી.',
      'grantUsagePermission': 'એપ વિગત જોવા માટે usage પરવાનગી આપો.',
      'usageAccessNeeded': 'યૂસેજ એક્સેસ જરૂરી છે',
      'usageAccessPrompt':
          'વાસ્તવિક સ્ક્રીન સમય ડેટા વાંચવા માટે Android સેટિંગ્સમાં usage access ચાલુ કરો.',
      'openSettings': 'સેટિંગ્સ ખોલો',
      'refresh': 'રીફ્રેશ',
      'backgroundSyncUnavailable': 'બેકગ્રાઉન્ડ સિંક હજુ ઉપલબ્ધ નથી.',
      'lastBackgroundSync': 'છેલ્લો બેકગ્રાઉન્ડ સિંક',
      'trackedApps': 'ટ્રેક કરેલા એપ્સ',
      'today': 'આજે',
      'signInToViewInsights': 'ઇન્સાઇટ્સ જોવા સાઇન ઇન કરો.',
      'insightsLoadFailed': 'હમણાં ઇન્સાઇટ્સ લોડ થઈ શકી નથી.',
      'insightsSubtitle': 'તમારો સાપ્તાહિક વેલબીંગ રિપોર્ટ',
      'noInsightsYet': 'હજુ ઇન્સાઇટ્સ નથી',
      'unlockInsightsHint':
          'ફોકસ સેશન પૂર્ણ કરો, હેબિટ્સ લોગ કરો અને ટ્રેન્ડ્સ અનલોક કરવા એક દિવસ એપનો ઉપયોગ કરો.',
      'thisWeek': 'આ અઠવાડિયું',
      'thisMonth': 'આ મહિનો',
      'overDailyLimit': 'દૈનિક મર્યાદા કરતાં વધુ',
      'withinDailyLimit': 'દૈનિક મર્યાદામાં',
      'tapBarToInspectDay': 'દિવસની વિગતો જોવા બાર પર ટેપ કરો',
      'setDailyScreenTimeHint': 'દરરોજ કેટલો સ્ક્રીન સમય જોઈએ તે સેટ કરો',
      'signInToViewHabits': 'તમારી હેબિટ્સ જોવા સાઇન ઇન કરો.',
      'productive': 'ઉત્પાદક',
      'entertainment': 'મનોરંજન',
      'social': 'સોશિયલ',
      'focusMode': 'ફોકસ મોડ',
      'fatigueTracker': 'થકાવટ ટ્રેકર',
      'habits': 'Daily Rhythm',
      'appCategorizer': 'એપ વર્ગીકરણ',
      'fatigueAutoDetected': 'તમારા ઉપયોગ પેટર્ન પરથી આપમેળે શોધાયું',
      'fatigueUsageLimited': 'યૂસેજ એક્સેસ ચાલુ નથી. થકાવટ સ્કોર હાલમાં મર્યાદિત ડેટા પર છે.',
      'enable': 'ચાલુ કરો',
      'fatigueLevelFresh': 'તાજું',
      'fatigueLevelMild': 'હળવી થાક',
      'fatigueLevelModerate': 'મધ્યમ થાક',
      'fatigueLevelHigh': 'ઉંચી થાક',
      'fatigueRecoFresh': 'તમે સારી સ્થિતિમાં છો! આજે તમારી ડિજિટલ આદતો સ્વસ્થ છે.',
      'fatigueRecoMild': 'હળવી થાક મળી. થોડું ચાલો અથવા સ્ટ્રેચ કરો.',
      'fatigueRecoModerate': 'મધ્યમ થાક. 30+ મિનિટ સ્ક્રીનથી દૂર રહો.',
      'fatigueRecoHigh': 'ઉંચી ડિજિટલ થાક. આંખોને આરામ આપો અને સ્ક્રીનથી દૂર રહો.',
      'after10pm': 'રાત્રે 10 પછી',
      'withoutBreak': 'બ્રેક વગર',
      'fatigueTriggerHighScreenTime': 'ઉચ્ચ સ્ક્રીન સમય',
      'fatigueTriggerLateNight': 'મોડી રાત્રે ઉપયોગ મળ્યો',
      'fatigueTriggerLongSession': 'લાંબો સતત સેશન',
      'fatigueTriggerHeavyDraining': 'સોશિયલ/મનોરંજનનો ભારે ઉપયોગ',
      'fatigueTriggerNoFocusToday': 'આજે કોઈ ફોકસ સેશન પૂર્ણ થયું નથી',
      'fatigueScore': 'થકાવટ સ્કોર',
      'scoreBreakdown': 'સ્કોર વિગત',
      'drainingApps': 'થકાવટ આપતા એપ્સ',
      'lateNightUse': 'મોડી રાત્રે ઉપયોગ',
      'longSessions': 'લાંબા સેશન',
      'healthyHabitsMinus': 'સ્વસ્થ હેબિટ્સ (-)',
      'fatigueHistory7Days': '7-દિવસ થકાવટ ઇતિહાસ',
      'noFatigueDataYet': 'હજી થકાવટ ડેટા નથી. એપનો ઉપયોગ ચાલુ રાખો, ચાર્ટ ભરાશે.',
      'fatigueTriggers': 'થકાવટ ટ્રિગર',
      'recommendation': 'ભલામણ',
      'mon': 'સોમ',
      'tue': 'મંગળ',
      'wed': 'બુધ',
      'thu': 'ગુરુ',
      'fri': 'શુક્ર',
      'sat': 'શનિ',
      'sun': 'રવિ',
      'appCategories': 'એપ કેટેગરી',
      'autoCategorizedByUsage': 'ઉપયોગ પેટર્ન પરથી આપમેળે વર્ગીકૃત',
      'usageHealth': 'ઉપયોગ આરોગ્ય',
      'healthy': 'સ્વસ્થ',
      'draining': 'થકાવટકારક',
      'categoryBreakdown': 'કેટેગરી વિગત',
      'all': 'બધા',
      'grantUsagePermissionCategories': 'એપ કેટેગરી જોવા માટે યૂસેજ પરવાનગી આપો.',
      'habitsSubtitle': 'તમારી દૈનિક રૂટિન બનાવો',
      'todaysHabits': 'આજની હેબિટ્સ',
      'noHabitsYet': 'હજુ હેબિટ્સ નથી',
      'tapAddHabitFirst': 'તમારી પ્રથમ હેબિટ બનાવવા Add Habit દબાવો.',
      'todayProgress': 'આજની પ્રગતિ',
      'complete': 'પૂર્ણ',
      'totalStreakDays': 'કુલ સ્ટ્રીક દિવસ',
      'addHabit': 'હેબિટ ઉમેરો',
      'newHabit': 'નવી હેબિટ',
      'chooseEmoji': 'ઇમોજી પસંદ કરો',
      'habitName': 'હેબિટનું નામ',
      'habitNameHint': 'ઉદાહરણ: પાણી પીવું, વ્યાયામ...',
      'reminderTime': 'રિમાઇન્ડર સમય',
      'setRepeatInterval': 'રીપીટ ઇન્ટરવલ સેટ કરો',
      'repeatEveryMinutes': 'દર {minutes} મિનિટે રીપીટ',
      'noRepeatInterval': 'કોઈ રીપીટ ઇન્ટરવલ નથી',
      'editHabit': 'હેબિટ સંપાદિત કરો',
      'removeHabit': 'હેબિટ દૂર કરો',
      'confirmRemoveHabit': '"{name}" દૂર કરીને તેના રિમાઇન્ડર રદ કરશો?',
      'dayStreak': 'દિવસ સ્ટ્રીક',
      'past7Days': 'છેલ્લા 7 દિવસ',
      'past30Days': 'છેલ્લા 30 દિવસ',
      'noHabitLogsYet': 'આ સમયગાળા દરમિયાન હજી હેબિટ લોગ નથી.',
      'weeklyInsights': 'સાપ્તાહિક ઇન્સાઇટ્સ',
      'avgScore': 'સરેરાશ સ્કોર',
      'avgFatigue': 'સરેરાશ થકાવટ',
      'focusShort': 'ફોકસ',
      'wellbeingWord': 'વેલબીંગ',
      'thisWeekLower': 'આ અઠવાડિયે',
      'thisMonthLower': 'આ મહિને',
      'wellbeingTrend': 'વેલબીંગ ટ્રેન્ડ',
      'weeklyAppUsageBreakdown': 'સાપ્તાહિક એપ ઉપયોગ વિગત',
      'productiveVsDraining': 'ઉત્પાદક સામે થકાવટકારક',
      'friend': 'મિત્ર',
      'goodMorning': 'સુપ્રભાત',
      'goodAfternoon': 'નમસ્તે',
      'goodEvening': 'શુભ સાંજ',
      'focusModeSubtitleBreak': 'થોડી રાહત લો',
      'focusModeSubtitleFocus': 'ફોકસમાં રહો',
      'sessionsToday': 'આજે સેશન',
      'focusedToday': 'આજે ફોકસ સમય',
      'breakTime': 'બ્રેક સમય',
      'sessionDurations': 'સેશન અવધિ',
      'adjustTimesRoutine': 'સમય તમારી રૂટિન મુજબ ગોઠવો.',
      'resetDefaults': 'ડિફોલ્ટ રીસેટ',
      'durationsReset': 'ફોકસ અવધિઓ ડિફોલ્ટ પર રીસેટ થઈ.',
      'sessionCompleteTakeBreak': 'સેશન પૂર્ણ! બ્રેક લો.',
      'breakOverReadyFocus': 'બ્રેક પૂરી. ફોકસ માટે તૈયાર?',
      'minutesShort': 'મિન',
      'readyToFocus': 'ફોકસ માટે તૈયાર?',
      'startPomodoro': 'પોમોડોરો સેશન શરૂ કરો',
      'start': 'શરૂ',
      'cloudSynced': 'ક્લાઉડ સિંક',
      'pendingUpload': 'અપલોડ બાકી',
      'usingOfflineCache': 'ઓફલાઇન કેશ ઉપયોગમાં',
      'waitingFirstSync': 'પ્રથમ બેકગ્રાઉન્ડ સિંકની રાહ...',
      'lastSync': 'છેલ્લો સિંક',
      'trackedAppsTitle': 'ટ્રેક કરેલા એપ્સ',
      'habitConsistency': 'હેબિટ સતતતા',
      'daysWord': 'દિવસ',
      'insightAvgWellbeingPrefix': 'આ સમયગાળામાં તમારું સરેરાશ વેલબીંગ છે',
      'insightAvgFatiguePrefix': 'સરેરાશ થાક છે',
      'insightOutOf100': '100 માંથી',
      'insightFocusCompletedPrefix': 'તમે પૂર્ણ કર્યા',
      'insightFocusCompletedSuffix': 'ફોકસ સેશન છેલ્લા',
      'insightProductiveRatioPrefix': 'ઉત્પાદક ઉપયોગ અનુપાત',
      'insightProductiveRatioSuffix': 'તમારા લોગ ડેટા પર આધારિત છે',
      'wellbeingScore': 'વેલબીંગ સ્કોર',
      'basedOnTodaysFatigue': 'આજના થકાવટ સ્કોર પર આધારિત',
      'noHabitsHomeHint': 'હજુ હેબિટ્સ નથી. Daily Rhythm ટેબમાં ઉમેરો, અહીં તરત દેખાશે.',
      'fatigueHighHint': 'બ્રેક લો અને થકાવટકારક એપ ઉપયોગ ઘટાડો.',
      'fatigueModerateHint': 'ટૂંકું રિકવરી બ્રેક તમારા માટે સારું છે.',
      'fatigueMildHint': 'સારો બેલેન્સ છે. સ્ક્રીન ઉપયોગ સચેત રાખો.',
      'fatigueLowLabel': 'ઓછી થકાવટ',
      'fatigueLowHint': 'આજે તમારી ઊર્જા પેટર્ન ઉત્તમ છે.',
      'doneWord': 'પૂર્ણ',
      'pomodoro': 'પોમોડોરો',
      'deepWork': 'ડીપ વર્ક',
      'flowState': 'ફ્લો સ્ટેટ',
      'focusTip1': 'સેશન દરમિયાન ફોન ઉંધો રાખો',
      'focusTip2': 'એકાગ્રતા માટે લોફાઇ સંગીત અજમાવો',
      'focusTip3': 'હાઇડ્રેટ રહેવા પાણી નજીક રાખો',
      'focusTip4': 'ડેસ્ક પર છોડ તણાવ ઘટાડે છે',
      'focusTip5': 'શરૂ કરતાં પહેલાં Do Not Disturb ચાલુ કરો',
    },
  };

  String tr(String key) {
    final lang = _strings[locale.languageCode] ?? _strings['en']!;
    return lang[key] ?? _strings['en']![key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .any((l) => l.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}

extension AppLocalizationsContextX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
